# -*- coding: utf-8 -*-
"""newapp.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhdBugkcZf7HJh5yg73UlH96wEcqNv3E
"""

import joblib
import streamlit as st
import pandas as pd

# Load the saved model and scaler
model = joblib.load('price_forecasting_model.pkl')
scaler = joblib.load('scaler.pkl')

# Define the Streamlit app
def app():
    st.title("🌟 Energy Demand and Price Prediction App")
    st.markdown("This app predicts **total energy load** and **price forecasts** based on user inputs.")

    # Tabs for Input and Output
    tab1, tab2 = st.tabs(["⚙️ Input Features", "📊 Prediction Results"])

    # Input Features Tab
    with tab1:
        st.subheader("Provide the following details:")
        col1, col2 = st.columns(2)

        with col1:
            total_load_forecast = st.slider("Total Load Forecast (MW)", value=0.0, step=0.1)
            renewable_generation = st.slider("Renewable Generation (MW)", value=0.0, step=0.1)
            hour = st.slider("Hour of Day", 0, 23, value=12)

        with col2:
            price_day_ahead = st.slider("Price Day Ahead (€/MWh)", value=0.0)
            fossil_generation = st.slider("Fossil Generation (MW)", value=0.0, step=0.1)
            price_actual = st.slider("Price Actual (€/MWh)", value=0.0, step=0.1)
            day_of_week = st.selectbox("Day of Week", options=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], index=0)
            year = st.selectbox("Year", options=[2025, 2026, 2027], index=0)

        month = st.selectbox("Month", options=list(range(1, 13)), format_func=lambda x: f"Month {x}")

        st.markdown("### Summary of Input Features")
        st.write({
            "Total Load Forecast": total_load_forecast,
            "Renewable Generation": renewable_generation,
            "Fossil Generation": fossil_generation,
            "Price Day Ahead": price_day_ahead,
            "Hour": hour,
            "Day of Week": day_of_week,
            "Month": month,
            "Year": year
        })

    # Prediction Results Tab
    with tab2:
        st.subheader("Results")
        if st.button("Predict Price"):
            if model:
                # Prepare input data for price prediction
                input_data = pd.DataFrame({
                    'total load forecast': [total_load_forecast],
                    'renewable_generation': [renewable_generation],
                    'fossil_generation': [fossil_generation],
                    'price_day_ahead': [price_day_ahead],
                    'hour': [hour],
                    'day_of_week': [day_of_week],
                    'month': [month],
                    'year': [year]
                })

                # Scale the input features using the same scaler
                input_data_scaled = scaler.transform(input_data)

                # Predict price
                predicted_price = model.predict(input_data_scaled)[0]

                st.success(f"Predicted Price: {predicted_price:,.2f} €/MWh")
            else:
                st.error("Price prediction model is not loaded.")

# Run the app
if __name__ == "__main__":
    app()

